-- AlterTable
ALTER TABLE "DocumentPriceChangeItem" ALTER COLUMN "oldValue" SET DATA TYPE DECIMAL(15,4),
ALTER COLUMN "newValue" SET DATA TYPE DECIMAL(15,4);

-- AlterTable
ALTER TABLE "DocumentPurchaseItem" ALTER COLUMN "price" SET DATA TYPE DECIMAL(15,4);

-- AlterTable
ALTER TABLE "DocumentReturnItem" ALTER COLUMN "price" SET DATA TYPE DECIMAL(15,4);

-- AlterTable
ALTER TABLE "DocumentSaleItem" ALTER COLUMN "price" SET DATA TYPE DECIMAL(15,4),
ALTER COLUMN "costPrice" SET DATA TYPE DECIMAL(15,4);

-- AlterTable
ALTER TABLE "Price" ALTER COLUMN "value" SET DATA TYPE DECIMAL(15,4);

-- AlterTable
ALTER TABLE "PriceLedger" ALTER COLUMN "valueBefore" SET DATA TYPE DECIMAL(15,4),
ALTER COLUMN "value" SET DATA TYPE DECIMAL(15,4);

-- AlterTable
ALTER TABLE "Stock" ALTER COLUMN "averagePurchasePrice" SET DATA TYPE DECIMAL(15,4);

-- AlterTable
ALTER TABLE "StockLedger" ALTER COLUMN "averagePurchasePrice" SET DATA TYPE DECIMAL(15,4);
